version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_NAME=library_db
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_db
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - '8080:80'
    depends_on:
      - mysql

volumes:
  mysql_data:
